version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/friend-lines
      - JWT_SECRET=your-secret-key-change-in-production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - friend-lines-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=friend-lines
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - friend-lines-network

volumes:
  mongo_data:

networks:
  friend-lines-network:
    driver: bridge
